modLoader="javafml"
loaderVersion="[47,)" # 根據 Forge 版本選對（54.1.x 用這個 OK）

license="MIT"

[[mods]]
modId="cursedweather"
version="1.0.0"
displayName="Cursed Weather"
description='''
每 5 分鐘世界會發生災難，每次睡覺都可能是最後一次。 Disasters happen every 5 minutes.
'''

[[dependencies.cursedweather]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
